config/urls.py
from django.contrib import admin
from django.urls import path, include
from students.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('groups/', include('groups.urls')),
    path('teachers/', include('teachers.urls')),
    path('', home, name='home')

]

groups/urls.py
from django.urls import path
from . import views


app_name = 'groups'

urlpatterns = [
    path('group/', views.group_list, name='groups'),
    path('create/', views.group_create, name='create'),
    path('detail/<int:pk>/', views.group_delete, name='detail'),
    path('delete/<int:pk>/', views.group_delete, name='delete'),
]

students/urls.py
from django.urls import path
from . import views


app_name = 'students'

urlpatterns = [
    path('list/', views.student_list, name='list'),
    path('create/', views.students_create, name='create'),
    path('detail/<int:pk>/', views.student_detail, name='detail'),
    path('delete/<int:pk>/', views.student_delete, name='delete'),
]

teachers/urls.py
from django.urls import path
from . import views


app_name = 'teachers'

urlpatterns = [
    path('list/', views.teacher_list, name='teachers'),
    path('create/', views.teacher_create, name='create'),
    path('detail/<int:pk>/', views.teacher_detail, name='detail'),
    path('delete/<int:pk>/', views.teacher_delete, name='delete'),
]

groups/models.py
from django.db import models


class Group(models.Model):
    group_name = models.CharField(max_length=100)
    group_type = models.CharField(max_length=100)

students/models.py
from django.db import models


class Student(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    age = models.PositiveIntegerField()
    email = models.EmailField()

teachers/models.py
from django.db import models


class Teacher(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)

groups/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Group


def group_list(request):
    groups = Group.objects.all()
    ctx = {'groups': groups}
    return render(request, 'groups/groups-list.html', ctx)


def group_create(request):
    if request.method == 'POST':
        group_name = request.POST.get('group_name')
        group_type = request.POST.get('group_type')
        if group_name and group_type:
            Group.objects.create(
                group_name=group_name,
                group_type=group_type,
            )
            return redirect('groups:groups')
    return render(request, 'groups/groups-form.html')


def group_detail(request, pk):
    groups = get_object_or_404(Group, pk=pk)
    ctx = {'groups': groups}
    return render(request, 'groups/detail.html', ctx)


def group_delete(request, pk):
    groups = get_object_or_404(Group, pk=pk)
    groups.delete()
    return redirect('groups:groups')

students/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Student


def home(request):
    return render(request, 'index.html')


def student_list(request):
    students = Student.objects.all()
    ctx = {'students': students}
    return render(request, 'students/students-list.html', ctx)


def students_create(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        age = request.POST.get('age')
        email = request.POST.get('email')
        if first_name and last_name and age and email:
            Student.objects.create(
                first_name=first_name,
                last_name=last_name,
                age=age,
                email=email,
            )
            return redirect('students:list')
    return render(request, 'students/students-form.html')


def student_detail(request, pk):
    students = get_object_or_404(Student, pk=pk)
    ctx = {'students': students}
    return render(request, 'students/detail.html', ctx)


def student_delete(request, pk):
    students = get_object_or_404(Student, pk=pk)
    students.delete()
    return redirect('students:list')

teachers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Teacher


def teacher_list(request):
    teachers = Teacher.objects.all()
    ctx = {'teachers': teachers}
    return render(request, 'teachers/teachers-list.html', ctx)


def teacher_create(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        subject = request.POST.get('subject')
        if first_name and last_name and subject:
            Teacher.objects.create(
                first_name=first_name,
                last_name=last_name,
                subject=subject,
            )
            return redirect('teachers:teachers')
    return render(request, 'teachers/teachers-form.html')


def teacher_detail(request, pk):
    teachers = get_object_or_404(Teacher, pk=pk)
    ctx = {'teachers': teachers}
    return render(request, 'teachers/detail.html', ctx)


def teacher_delete(request, pk):
    teachers = get_object_or_404(Teacher, pk=pk)
    teachers.delete()
    return redirect('teachers:teachers')

templates/groups/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ groups.title }}</title>
</head>
<body>
    <h1>{{ groups.group_name }} {{ groups.group_name }}</h1>
    <h3>Details:</h3>
    <h3>Group Name: {{ groups.group_name }}</h3>
    <h3>Group Type: {{ groups.group_type }}</h3>
    <a href="{% url 'groups:delete' pk=groups.pk %}">Delete</a><br>
    <a href="{% url 'groups:groups' %}">Back to list</a>
</body>
</html>

templates/groups/groups-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Groups</title>
</head>
<body>
    <h1>Create Groups</h1>
    <form method="post">
        {% csrf_token %}
        <label for="group_name">Group Name</label><br>
        <input type="text" name="group_name" id="group_name" required><br>

        <label for="group_type">Group Type</label><br>
        <input type="text" name="group_type" id="group_type" required><br>
        <input type="submit" value="Create groups">
    </form>

</body>
</html>

templates/groups/groups-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Group List</title>
</head>
<body>
    <h1>Group List</h1>
    <a href="{% url 'groups:create' %}">Create Group</a>
    {% for groups in groups %}
    <a href="{% url 'groups:detail' pk=groups.pk %}"><h3>{{ groups.group_name }} {{ groups.group_type }}</h3></a>
    {% empty %}
        <h3>Not found</h3>
    {% endfor %}
    <a href="{% url 'home' %}">Back to home</a>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h1>Home</h1>
    <a href="{% url 'students:list' %}"><h3>Student List</h3></a>
    <a href="{% url 'groups:groups' %}"><h3>Group List</h3></a>
    <a href="{% url 'teachers:teachers' %}"><h3>Teacher List</h3></a>
</body>
</html>

templates/students/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ students.title }}</title>
</head>
<body>
    <h1>{{ students.first_name }} {{ students.last_name }}</h1>
    <h3>Details:</h3>
    <h3>Age: {{ students.age }}</h3>
    <h3>Email: {{ students.email }}</h3>
    <a href="{% url 'students:delete' pk=students.pk %}">Delete</a><br>
    <a href="{% url 'students:list' %}">Back to home</a>
</body>
</html>

templates/students/students-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Student</title>
</head>
<body>
    <h1>Create Student</h1>
    <form method="post">
        {% csrf_token %}
        <label for="first_name">First Name</label><br>
        <input type="text" name="first_name" id="first_name" required><br>

        <label for="last_name">Last Name</label><br>
        <input type="text" name="last_name" id="last_name"><br>

        <label for="age">Age</label><br>
        <input type="number" name="age" id="age"><br>

        <label for="email">Email</label><br>
        <input type="text" name="email" id="email"><br>
        <input type="submit" value="Create students">
    </form>
</body>
</html>

templates/students/students-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student List</title>
</head>
<body>
    <h1>Student List</h1>
    <a href="{% url 'students:create' %}">Create Student</a>
    {% for students in students %}
        <a href="{% url 'students:detail' pk=students.pk %}"><h3>{{ students.first_name }} {{ students.last_name }}</h3></a>
    {% empty %}
        <h3>Not found</h3>
    {% endfor %}
    <a href="{% url 'home' %}">Back to home</a>

</body>
</html>

templates/teachers/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ teachers.title }}</title>
</head>
<body>
    <h1>{{ teachers.first_name }} {{ teachers.last_name }}</h1>
    <h3>Details:</h3>
    <h3>Subject: {{ teachers.subject }}</h3>
    <a href="{% url 'teachers:delete' pk=teachers.pk %}">Delete</a><br>
    <a href="{% url 'teachers:teachers' %}">Back to list</a>
</body>
</html>

templates/teachers/teachers-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Teachers</title>
</head>
<body>
    <h1>Create Teachers</h1>
    <form method="post">
        {% csrf_token %}
        <label for="first_name">First Name</label><br>
        <input type="text" name="first_name" id="first_name" required><br>

        <label for="last_name">Last Name</label><br>
        <input type="text" name="last_name" id="last_name" required><br>

        <label for="subject">Subject</label><br>
        <input type="text" name="subject" id="subject"><br>
        <input type="submit" value="Create person">
    </form>
</body>
</html>

templates/teachers/teachers-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teachers List</title>
</head>
<body>
    <h1>Teachers List</h1>
    <a href="{% url 'teachers:create' %}">Create Teachers</a>
    {% for teachers in teachers %}
    <a href="{% url 'teachers:detail' pk=teachers.pk %}"><h3>{{ teachers.first_name }} {{ teachers.last_name }}</h3></a>
    {% empty %}
        <h3>Not found</h3>
    {% endfor %}
    <a href="{% url 'home' %}">Back to home</a>

</body>
</html>